import 'package:flutter/material.dart';

class AppColorSchemes {
  // Generated Light Color Scheme
  static const ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff00687a),
    surfaceTint: Color(0xff00687a),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffadecff),
    onPrimaryContainer: Color(0xff004e5d),
    secondary: Color(0xff4b6269),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffcee7ef),
    onSecondaryContainer: Color(0xff334a51),
    tertiary: Color(0xff575c7e),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffdee1ff),
    onTertiaryContainer: Color(0xff3f4565),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff93000a),
    surface: Color(0xfff5fafc),
    onSurface: Color(0xff171c1e),
    onSurfaceVariant: Color(0xff3f484b),
    outline: Color(0xff70797c),
    outlineVariant: Color(0xffbfc8cb),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2c3133),
    inversePrimary: Color(0xff85d2e7),
    primaryFixed: Color(0xffadecff),
    onPrimaryFixed: Color(0xff001f26),
    primaryFixedDim: Color(0xff85d2e7),
    onPrimaryFixedVariant: Color(0xff004e5d),
    secondaryFixed: Color(0xffcee7ef),
    onSecondaryFixed: Color(0xff061f25),
    secondaryFixedDim: Color(0xffb2cbd3),
    onSecondaryFixedVariant: Color(0xff334a51),
    tertiaryFixed: Color(0xffdee1ff),
    onTertiaryFixed: Color(0xff131937),
    tertiaryFixedDim: Color(0xffbfc4eb),
    onTertiaryFixedVariant: Color(0xff3f4565),
    surfaceDim: Color(0xffd5dbdd),
    surfaceBright: Color(0xfff5fafc),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xffeff4f7),
    surfaceContainer: Color(0xffe9eff1),
    surfaceContainerHigh: Color(0xffe4e9eb),
    surfaceContainerHighest: Color(0xffdee3e5),
    // Deprecated, but included for compatibility
    background: Color(0xfff5fafc),
    onBackground: Color(0xff171c1e),
    surfaceVariant: Color(0xffdce4e8),
  );

  // Generated Dark Color Scheme
  static const ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xff85d2e7),
    surfaceTint: Color(0xff85d2e7),
    onPrimary: Color(0xff003641),
    primaryContainer: Color(0xff004e5d),
    onPrimaryContainer: Color(0xffadecff),
    secondary: Color(0xffb2cbd3),
    onSecondary: Color(0xff1d343a),
    secondaryContainer: Color(0xff334a51),
    onSecondaryContainer: Color(0xffcee7ef),
    tertiary: Color(0xffbfc4eb),
    onTertiary: Color(0xff292e4d),
    tertiaryContainer: Color(0xff3f4565),
    onTertiaryContainer: Color(0xffdee1ff),
    error: Color(0xffffb4ab),
    onError: Color(0xff690005),
    errorContainer: Color(0xff93000a),
    onErrorContainer: Color(0xffffdad6),
    surface: Color(0xff0f1416),
    onSurface: Color(0xffdee3e5),
    onSurfaceVariant: Color(0xffbfc8cb),
    outline: Color(0xff899295),
    outlineVariant: Color(0xff3f484b),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffdee3e5),
    inversePrimary: Color(0xff00687a),
    primaryFixed: Color(0xffadecff),
    onPrimaryFixed: Color(0xff001f26),
    primaryFixedDim: Color(0xff85d2e7),
    onPrimaryFixedVariant: Color(0xff004e5d),
    secondaryFixed: Color(0xffcee7ef),
    onSecondaryFixed: Color(0xff061f25),
    secondaryFixedDim: Color(0xffb2cbd3),
    onSecondaryFixedVariant: Color(0xff334a51),
    tertiaryFixed: Color(0xffdee1ff),
    onTertiaryFixed: Color(0xff131937),
    tertiaryFixedDim: Color(0xffbfc4eb),
    onTertiaryFixedVariant: Color(0xff3f4565),
    surfaceDim: Color(0xff0f1416),
    surfaceBright: Color(0xff343a3c),
    surfaceContainerLowest: Color(0xff090f11),
    surfaceContainerLow: Color(0xff171c1e),
    surfaceContainer: Color(0xff1b2022),
    surfaceContainerHigh: Color(0xff252b2d),
    surfaceContainerHighest: Color(0xff303638),
    // Deprecated, but included for compatibility
    background: Color(0xff0f1416),
    onBackground: Color(0xffdee3e5),
    surfaceVariant: Color(0xff3f484b),
  );

  // Additional contrast variants (for accessibility)
  static const ColorScheme lightMediumContrastScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff003c48),
    surfaceTint: Color(0xff00687a),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xff1f778a),
    onPrimaryContainer: Color(0xffffffff),
    secondary: Color(0xff233940),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xff5a7178),
    onSecondaryContainer: Color(0xffffffff),
    tertiary: Color(0xff2f3453),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xff666b8d),
    onTertiaryContainer: Color(0xffffffff),
    error: Color(0xff740006),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffcf2c27),
    onErrorContainer: Color(0xffffffff),
    surface: Color(0xfff5fafc),
    onSurface: Color(0xff0c1214),
    onSurfaceVariant: Color(0xff2f383a),
    outline: Color(0xff4b5457),
    outlineVariant: Color(0xff666e72),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2c3133),
    inversePrimary: Color(0xff85d2e7),
    primaryFixed: Color(0xff1f778a),
    onPrimaryFixed: Color(0xffffffff),
    primaryFixedDim: Color(0xff005d6e),
    onPrimaryFixedVariant: Color(0xffffffff),
    secondaryFixed: Color(0xff5a7178),
    onSecondaryFixed: Color(0xffffffff),
    secondaryFixedDim: Color(0xff41585f),
    onSecondaryFixedVariant: Color(0xffffffff),
    tertiaryFixed: Color(0xff666b8d),
    onTertiaryFixed: Color(0xffffffff),
    tertiaryFixedDim: Color(0xff4d5374),
    onTertiaryFixedVariant: Color(0xffffffff),
    surfaceDim: Color(0xffc2c7ca),
    surfaceBright: Color(0xfff5fafc),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xffeff4f7),
    surfaceContainer: Color(0xffe4e9eb),
    surfaceContainerHigh: Color(0xffd8dee0),
    surfaceContainerHighest: Color(0xffcdd2d5),
    background: Color(0xfff5fafc),
    onBackground: Color(0xff0c1214),
    surfaceVariant: Color(0xffdce4e8),
  );

  static const ColorScheme darkMediumContrastScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xff9be8fe),
    surfaceTint: Color(0xff85d2e7),
    onPrimary: Color(0xff002a33),
    primaryContainer: Color(0xff4c9baf),
    onPrimaryContainer: Color(0xff000000),
    secondary: Color(0xffc8e1e9),
    onSecondary: Color(0xff11292f),
    secondaryContainer: Color(0xff7d959c),
    onSecondaryContainer: Color(0xff000000),
    tertiary: Color(0xffd6daff),
    onTertiary: Color(0xff1e2442),
    tertiaryContainer: Color(0xff898fb3),
    onTertiaryContainer: Color(0xff000000),
    error: Color(0xffffd2cc),
    onError: Color(0xff540003),
    errorContainer: Color(0xffff5449),
    onErrorContainer: Color(0xff000000),
    surface: Color(0xff0f1416),
    onSurface: Color(0xffffffff),
    onSurfaceVariant: Color(0xffd5dee1),
    outline: Color(0xffaab3b7),
    outlineVariant: Color(0xff899295),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffdee3e5),
    inversePrimary: Color(0xff004f5e),
    primaryFixed: Color(0xffadecff),
    onPrimaryFixed: Color(0xff001419),
    primaryFixedDim: Color(0xff85d2e7),
    onPrimaryFixedVariant: Color(0xff003c48),
    secondaryFixed: Color(0xffcee7ef),
    onSecondaryFixed: Color(0xff001419),
    secondaryFixedDim: Color(0xffb2cbd3),
    onSecondaryFixedVariant: Color(0xff233940),
    tertiaryFixed: Color(0xffdee1ff),
    onTertiaryFixed: Color(0xff080f2c),
    tertiaryFixedDim: Color(0xffbfc4eb),
    onTertiaryFixedVariant: Color(0xff2f3453),
    surfaceDim: Color(0xff0f1416),
    surfaceBright: Color(0xff404547),
    surfaceContainerLowest: Color(0xff04080a),
    surfaceContainerLow: Color(0xff191e20),
    surfaceContainer: Color(0xff23292b),
    surfaceContainerHigh: Color(0xff2e3335),
    surfaceContainerHighest: Color(0xff393f41),
    background: Color(0xff0f1416),
    onBackground: Color(0xffffffff),
    surfaceVariant: Color(0xff3f484b),
  );
}

// Custom color extensions for brand-specific colors
class AppColors {
  // Custom semantic colors
  static const Color success = Color(0xFF4CAF50);
  static const Color warning = Color(0xFFFF9800);
  static const Color info = Color(0xFF2196F3);

  // Brand colors (if different from theme)
  static const Color brandPrimary = Color(0xFF6750A4);
  static const Color brandSecondary = Color(0xFF625B71);

  // Gradient colors
  static const List<Color> primaryGradient = [
    Color(0xFF6750A4),
    Color(0xFF4F378B),
  ];

  static const List<Color> secondaryGradient = [
    Color(0xFF625B71),
    Color(0xFF4A4458),
  ];
}
