name: widu
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  authentication:
    path: packages/authentication
  cloud:
    path: packages/cloud
  flutter:
    sdk: flutter

  #bloc
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  #supabase
  supabase_flutter: ^2.8.1

  #ui
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  #shared_preferences is used for storing simple key-value data that persists between app sessions.
  shared_preferences: ^2.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  #for creating mock objects in unit tests
  mocktail: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/fonts/
    # - assets/rive/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appstore.png"