name: authentication
description: "Authentication package for widu app"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management (core to auth flows)
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # Backend
  supabase_flutter: ^2.8.1

  # Local storage for tokens/state
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4